1037412 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
999062 + 0 mapped (96.30% : N/A)
1037412 + 0 paired in sequencing
518706 + 0 read1
518706 + 0 read2
8 + 0 properly paired (0.00% : N/A)
999062 + 0 with itself and mate mapped
0 + 0 singletons (0.00% : N/A)
16052 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
